### ISSUE TITLE
Invalid tag/reference format with ghcr.io

### ISSUE THREAD

**Issue by rhblind** [cloudposse/github-action-docker-build-push#77]
Found a bug? Maybe our [Slack Community](https://cloudposse.com/slack) can help.

[![Slack Community](https://slack.cloudposse.com/for-the-badge.svg)](https://cloudposse.com/slack)

## Describe the Bug
Hello,
I'm trying to set up a Github Workflow that uses this action to create and publish a docker image to ghcr.io. 
I'm getting an error on the `Builder info` step

```
Error: buildx failed with: ERROR: invalid tag "ghcr.io//:sha-8cc8e90c5ebb6ff27df767484b7f95f9d70f3faa": invalid reference format
```

## Expected Behavior
I expect the default tags to work.

## Steps to Reproduce
Whenever a workflow action runs, see below.

## Screenshots
If applicable, add screenshots or logs to help explain your problem.

## Environment (please complete the following information):

**My (simplified) workflow config**

```yaml
name: Release
on:
  push:
    branches:
      - main
  release:
    type: [published]
permissions:
  contents: read
  packages: write
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and push
        uses: cloudposse/github-action-docker-build-push@v1.17.2
        with:
          registry: ghcr.io
          login: ${{ github.actor }}
          password: ${{ secrets.github_token }}
          organization: ${{ github.repository.owner.login }}
          repository: ${{ github.repository.name }}

```

## Additional Context

**Error output**

```yaml
```
